apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: java-service-istio-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP    
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: cloudnative-java-service-canary
spec:
  hosts:
  - "*"
  gateways:
  - java-service-istio-gateway
  http:
  - route:
    - destination:
        host: cloudnative-java-service-canary
        subset: cloudnative-java-service-canary
        port:
          number: 9191
  - match:
    - headers:
        channel:
          exact: mobile
    route:
    - destination:
        host: cloudnative-java-service-canary
        subset: cloudnative-java-service-canary-mobile
        port:
          number: 9191
        
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: cloudnative-java-service-canary
spec:
  host: "*"
  subsets:
  - name: cloudnative-java-service-canary-mobile
    labels:
      version: cloudnative-java-service-canary-mobile
  - name: cloudnative-java-service-canary
    labels:
      version: cloudnative-java-service-canary
          