apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cloudnative-java-service-ramped
spec:
  replicas: 2
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: cloudnative-java-service
    spec:
      containers:
      - image: stmalike/java-service:UPDATE2_0
        imagePullPolicy: IfNotPresent
        name: cloudnative-java-service
        ports:
         - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 40
          timeoutSeconds: 1
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 40
          timeoutSeconds: 1
          periodSeconds: 15   
        volumeMounts:
          - name: cloudnative-config
            mountPath: "/config" 
            readOnly: true
      volumes:
      - name: cloudnative-config
        configMap:
          name: cloudnative-config 
          items:
          - key: application.properties
            path: application.properties         