apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cloudnative-frontend
spec:
  replicas: 2
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: cloudnative-frontend
    spec:
      containers:
        - image: stmalike/frontend
          imagePullPolicy: Always
          name: cloudnative-frontend
          resources:
            limits:
              memory: "64Mi"
              cpu: "1"
            requests:
              memory: "64Mi"
              cpu: "0.5"
          ports:
            - containerPort: 80