apiVersion: v1
kind: Pod
metadata:
  name: cloudnative-frontend
  labels:
    app: cloudnative-frontend
spec:
  containers:
    - image: stmalike/frontend
      name: cloudnative-frontend
      resources:
        limits:
          memory: "64Mi"
          cpu: "1"
        requests:
          memory: "64Mi"
          cpu: "0.5"
      ports:
        - containerPort: 80