apiVersion: v1
kind: Service
metadata:
  name: cloudnative-go-service-lb
spec:
  type: LoadBalancer
  ports:
  - port: 8079
    protocol: TCP
    targetPort: 8079
  selector:
    app: cloudnative-go-service